---
- name: Watch for nginx stopped log message
  hosts: all
  sources:
    - name: nginx watchdog log
      ansible.eda.file:
        path: /var/log/watchdog-nginx.log

  rules:
    - name: Restart nginx if stopped
      condition: event.payload.line contains "nginx stopped"
      action:
        run_playbook:
          name: restart-nginx.yml
