---
- name: Restart Nginx if service stopped
  hosts: all
  sources:
    - ansible.eda.webhook:
        name: nginx_watchdog_webhook
        port: 5001

  rules:
    - name: Restart nginx if stopped
      condition: event.payload.message == "nginx stopped"
      action:
        run_job_template:
          name: Restart Nginx
          extra_vars:
            target_host: "{{ event.payload.host }}"
